#:kivy 1.11.1

<MainScreen>:
    name: "Main"

    BoxLayout:
        orientation:"vertical"
        Label:
            text: _("Hello World!")
            font_name: app.theme.font_name
            base_direction: languagesmanager().bidi()
        
        Button:
            text: _("Next screen")
            on_release: screensloader().DashboardChangeToScreen("Main", True)
            font_name: app.theme.font_name
            base_direction: languagesmanager().bidi()